### PR TITLE
Prevent access to pages that require a singer

### LINKED ISSUE #152: Bug: If not linked to an account the user shouldnt be able to perfom any use case where a sign is required
## Expected Behaviour 

If you are not signed with an account, the application should let you know when you try to perfom an action that requires a signature.

## Current Behaviour

If you are not logged, you can enter to Create Initiative and Create Organization forms and it fails when you try to submit them.

### PR DESCRIPTION
**Pull request by b-avb**
Closes #152

### CODE REVIEW

File: src/middlewares/is_signer_ready.rs [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+    i18: UseI18,
+    accounts: UseAccountsState,
+    mut notification: UseNotificationState,
+) -> impl FnOnce() -> Result<(), &'static str> {
+    move || {
+        if accounts.get_account().is_none() {
+            notification.handle_warning(&translate!(i18, "warnings.middleware.has_dao"));
+            Err("Failed to get account to sign")
+        } else {
+            log::warn!("Signer is ready");
```
Comment (olanod) [inline src/middlewares/is_signer_ready.rs:13]: it's a positive outcome, would a debug or trace work better?

File: src/middlewares/is_signer_ready.rs [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+use dioxus_std::{i18n::UseI18, translate};
+pub fn is_signer_ready(
+    i18: UseI18,
+    accounts: UseAccountsState,
+    mut notification: UseNotificationState,
+) -> impl FnOnce() -> Result<(), &'static str> {
+    move || {
+        if accounts.get_account().is_none() {
+            notification.handle_warning(&translate!(i18, "warnings.middleware.has_dao"));
+            Err("Failed to get account to sign")
```
Comment (olanod) [inline src/middlewares/is_signer_ready.rs:11]: How is this error going to be handled? is it going to be logged or shown to the user(then it would need i18n)?

Comment (b-avb) [reply src/middlewares/is_signer_ready.rs:11]: The notification uses i18n and displays a warning to the user. The error is just a resource for development.

**Review by olanod — APPROVED** [review]
